### ISSUE TITLE
Permission denied within docker container

### ISSUE THREAD

**Issue by houserockr** [Dullage/flatnotes#55]
I'm using the `docker-compose.yml` from the readme as follows:

```
version: "3" 

services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "<snip>"
      FLATNOTES_PASSWORD: "<snip>"
      FLATNOTES_SECRET_KEY: "aLongRandomSeriesOfCharacters"
    volumes:
      - ./data:/app/data
      - ./index:/app/data/.flatnotes
    ports:
      - 8080:80
    restart: unless-stopped
```

When I try to bring it up with `docker-compose up`, I get the following stacktrace:

```
flatnotes  | Traceback (most recent call last):
flatnotes  |   File "<frozen runpy>", line 198, in _run_module_as_main
flatnotes  |   File "<frozen runpy>", line 88, in _run_code
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/uvicorn/__main__.py", line 4, in <module>
flatnotes  |     uvicorn.main()
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
flatnotes  |     return self.main(*args, **kwargs)
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/click/core.py", line 1055, in main
flatnotes  |     rv = self.invoke(ctx)
flatnotes  |          ^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
flatnotes  |     return ctx.invoke(self.callback, **ctx.params)
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/click/core.py", line 760, in invoke
flatnotes  |     return __callback(*args, **kwargs)
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/uvicorn/main.py", line 404, in main
flatnotes  |     run(
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/uvicorn/main.py", line 569, in run
flatnotes  |     server.run()
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
flatnotes  |     return asyncio.run(self.serve(sockets=sockets))
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
flatnotes  |     return runner.run(main)
flatnotes  |            ^^^^^^^^^^^^^^^^
flatnotes  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
flatnotes  |     return self._loop.run_until_complete(task)
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
flatnotes  |     return future.result()
flatnotes  |            ^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/uvicorn/server.py", line 67, in serve
flatnotes  |     config.load()
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/uvicorn/config.py", line 477, in load
flatnotes  |     self.loaded_app = import_from_string(self.app)
flatnotes  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
flatnotes  |     module = importlib.import_module(module_str)
flatnotes  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
flatnotes  |     return _bootstrap._gcd_import(name[level:], package, level)
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
flatnotes  |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
flatnotes  |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
flatnotes  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
flatnotes  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
flatnotes  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
flatnotes  |   File "/app/flatnotes/main.py", line 27, in <module>
flatnotes  |     flatnotes = Flatnotes(config.data_path)
flatnotes  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/app/flatnotes/flatnotes.py", line 172, in __init__
flatnotes  |     self.index = self._load_index()
flatnotes  |                  ^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/app/flatnotes/flatnotes.py", line 196, in _load_index
flatnotes  |     return whoosh.index.create_in(
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/whoosh/index.py", line 102, in create_in
flatnotes  |     return FileIndex.create(storage, schema, indexname)
flatnotes  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/whoosh/index.py", line 425, in create
flatnotes  |     TOC.create(storage, schema, indexname)
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/whoosh/index.py", line 611, in create
flatnotes  |     toc.write(storage, indexname)
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/whoosh/index.py", line 676, in write
flatnotes  |     stream = storage.create_file(tempfilename)
flatnotes  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flatnotes  |   File "/home/flatnotes/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/whoosh/filedb/filestore.py", line 490, in create_file
flatnotes  |     fileobj = open(path, mode)
flatnotes  |               ^^^^^^^^^^^^^^^^
flatnotes  | PermissionError: [Errno 13] Permission denied: '/app/data/.flatnotes/_3_0.toc.1679147739.3350751'
```

- docker compose 2.9.0
- docker 23.0.1

```
# docker image inspect dullage/flatnotes | grep -i created
        "Created": "2023-03-17T12:33:00.0331812Z",
```

**Comment by houserockr** [comment]
Apologies! I missed the note

> Note: To use either of the options below, please ensure the current directory contains a folder called "data" and that it's writable by user 1000.

**Comment by houserockr** [comment]
It's cumbersome, but it works.

**Comment by crisqyxw** [comment]
```
flatnotes  | PermissionError: [Errno 13] Permission denied: '/app/data/.flatnotes'

flatnotes exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)

[+] Running 0/1
 ⠇ Container flatnotes  Stopping                                                                                                                                    1.8s
canceled

[root@iZj6cdja66l1trox8f3whxZ flatnotes]# ls -la

total 8
drwxr-xr-x   3 root root   44 Mar 18 23:47 .
dr-xr-x---. 22 root root 4096 Mar 18 23:47 ..
drwxr-xr-x   2 root root    6 Mar 18 23:47 data
-rw-r--r--   1 root root 1043 Mar 18 23:47 docker-compose.yml
```
Sorry, I seem to have a writable directory? But Flatnotes still reports an error.

**Comment by Dullage** [comment]
Hey @crisqyxw 👋. That data folder looks to be owned by `root` but needs to be owned by user `1000`. 

For security reasons flatnotes runs as non-privileged user 1000. 

In the future I plan on making this a bit friendlier e.g. being able to change user ids like linuxserver.io images.

**Comment by Dullage** [comment]
Relates to #26.
